#Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: 27112003Tt.

#Server
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

#Email_Cpnfig
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: nguyenkhanhdu956@gmail.com
EMAIL_PASSWORD: iazu jiub aoez wglq
VERIFY_EMAIL_HOST: http://localhost:8080

JWT_EXPIRATION: 86400000
JWT_SECRET: ${SECRET}